CREATE TABLE APRENDIZ 
(ID_APRENDIZ NUMBER(20) PRIMARY KEY, 
NOMBRES VARCHAR2(30) NOT NULL,
APELLIDOS VARCHAR2(30) NOT NULL, 
EMAIL VARCHAR2(50) UNIQUE NULL, 
TELEFONO VARCHAR2(30) NULL); 

INSERT INTO APRENDIZ VALUES (1,'Samuel Mena','Luque','NULL',314587695);
INSERT INTO APRENDIZ VALUES (2,'Fatima Carrera','Naia Avilés','fatimisd78@gmail.com',320485636);
INSERT INTO APRENDIZ VALUES (3,'Leo Mares','Peralta','NULL',3112786598);
INSERT INTO APRENDIZ VALUES (4,'Aaron Apodaca','Peralta','aarons7@gmail.com',NULL);
INSERT INTO APRENDIZ VALUES (5,'Miriam Tamez','Peralta','miri.ms785@gmail.com',315874598);

CREATE TABLE BKP_APRENDIZ AS SELECT * FROM APRENDIZ;

ALTER TABLE BKP_APRENDIZ RENAME COLUMN EMAIL TO MAIL;

UPDATE BKP_APRENDIZ SET MAIL=faltacorreo@fake.com WHERE MAIL=NULL;

DELETE FROM APRENDIZ WHERE MAIL=Peralta;
